name: BungeeSpeak
version: '${project.version}-b${BUILD_NUMBER}'
description: 'This plugin will display Teamspeak 3 server joins, quits and messages in Minecraft.'
main: de.redstoneworld.bungeespeak.BungeeSpeak
author: 'Phoenix616'
authors: [but2002, greycap, deathmarine, Firedroide]
website: 'https://github.com/RedstoneWorld/BungeeSpeak'
commands:
  bungeespeak:
    description: BungeeSpeak commands
    aliases: [ts]
    usage: Type /ts for help.
  bungeespeakadmin:
    description: BungeeSpeak admin commands
    aliases: [tsa]
    usage: Type /tsa for help.
permissions:
  bungeespeak.*:
    description: Gives access to all BungeeSpeak commands and messages.
    default: op
    children:
      bungeespeak.commands.*: true
      bungeespeak.messages.*: true
  bungeespeak.moderator:
    description: Gives access to all user commands, all the messages and some admin commands.
    children:
      bungeespeak.commands.user: true
      bungeespeak.commands.channelkick: true
      bungeespeak.commands.reload: true
      bungeespeak.commands.status: true
      bungeespeak.messages.*: true
  bungeespeak.user:
    description: Gives access to most of the user commands and all messages.
    children:
      bungeespeak.commands.help: true
      bungeespeak.commands.list: true
      bungeespeak.commands.mute: true
      bungeespeak.commands.chat: true
      bungeespeak.commands.pm: true
      bungeespeak.commands.reply: true
      bungeespeak.commands.info: true
      bungeespeak.messages.*: true
  bungeespeak.commands.*:
    description: Gives access to all BungeeSpeak commands.
    children:
      bungeespeak.commands.user: true
      bungeespeak.commands.admin: true
  bungeespeak.commands.user:
    description: Gives access to all user commands.
    children:
      bungeespeak.commands.help: true
      bungeespeak.commands.list: true
      bungeespeak.commands.mute: true
      bungeespeak.commands.broadcast: true
      bungeespeak.commands.chat: true
      bungeespeak.commands.pm: true
      bungeespeak.commands.reply: true
      bungeespeak.commands.poke: true
      bungeespeak.commands.info: true
  bungeespeak.commands.admin:
    description: Gives access to all admin commands.
    children:
      bungeespeak.commands.ban: true
      bungeespeak.commands.kick: true
      bungeespeak.commands.channelkick: true
      bungeespeak.commands.set: true
      bungeespeak.commands.status: true
      bungeespeak.commands.reload: true
  bungeespeak.commands.help:
    description: Allows you to show BungeeSpeak's help menu.
    default: true
  bungeespeak.commands.list:
    description: Allows you to use /ts list.
  bungeespeak.commands.mute:
    description: Allows you to use /ts mute.
  bungeespeak.commands.broadcast:
    description: Allows you to use /ts broadcast <message>.
  bungeespeak.commands.chat:
    description: Allows you to use /ts chat <message>.
  bungeespeak.commands.pm:
    description: Allows you to use /ts pm target <message>.
  bungeespeak.commands.reply:
    description: Allows you to use /ts r(eply) <message>.
  bungeespeak.commands.poke:
    description: Allows you to use /ts poke <target> <message>.
  bungeespeak.commands.info:
    description: Allows you to use /ts info.
  bungeespeak.commands.ban:
    description: Allows you to use /tsa ban <target> (reason).
  bungeespeak.commands.kick:
    description: Allows you to use /tsa kick <target> (reason).
  bungeespeak.commands.channelkick:
    description: Allows you to use /tsa channelkick <target> (reason).
  bungeespeak.commands.set:
    description: Allows you to use /tsa set (property) (value).
  bungeespeak.commands.status:
    description: Allows you to use /tsa status.
  bungeespeak.commands.reload:
    description: Allows you to use /tsa reload.
  bungeespeak.messages.*:
    description: Allows you to see all messages.
    children:
      bungeespeak.messages.join: true
      bungeespeak.messages.leave: true
      bungeespeak.messages.channelenter: true
      bungeespeak.messages.channelleave: true
      bungeespeak.messages.broadcast: true
      bungeespeak.messages.chat: true
      bungeespeak.messages.pm: true
  bungeespeak.messages.join:
    description: Displays a message when somebody joined TeamSpeak.
  bungeespeak.messages.leave:
    description: Displays a message when somebody left TeamSpeak.
  bungeespeak.messages.channelenter:
    description: Displays a message when somebody entered the channel BungeeSpeak is listening to.
  bungeespeak.messages.channelleave:
    description: Displays a message when somebody left the channel BungeeSpeak is listening to.
  bungeespeak.messages.broadcast:
    description: Shows you messages which were broadcasted on TeamSpeak.
  bungeespeak.messages.chat:
    description: Shows you chat messages in the channel BungeeSpeak is listening to.
  bungeespeak.messages.pm:
    description: Shows you a message if somebody replies to your private message.
  bungeespeak.sendteamspeak.*:
    description: All messages will be sent to TeamSpeak.
    default: true
    children:
      bungeespeak.sendteamspeak.chat: true
      bungeespeak.sendteamspeak.join: true
      bungeespeak.sendteamspeak.quit: true
      bungeespeak.sendteamspeak.kick: true
      bungeespeak.sendteamspeak.ban: true
  bungeespeak.sendteamspeak.chat:
    description: Sends messages of this user to TeamSpeak if SendChatToTeamspeak is set in the config.
  bungeespeak.sendteamspeak.join:
    desctiption: Sends a Teamspeak message when the user joins the Minecraft server.
  bungeespeak.sendteamspeak.quit:
    description: Sends a Teamspeak message when the user leaves the Minecraft server.
  bungeespeak.sendteamspeak.kick:
    description: Sends a Teamspeak message when the user gets kicked from the Minecraft server.
  bungeespeak.sendteamspeak.ban:
    description: Sends a Teamspeak message when the user gets banned from the Minecraft server.
