name: BungeeSpeak
version: '${project.version}-b${BUILD_NUMBER}'
description: 'This plugin will display Teamspeak 3 server joins, quits and messages in Minecraft.'
main: de.redstoneworld.bungeespeak.BungeeSpeak
author: 'Firedroide'
authors: [but2002, greycap, deathmarine, Phoenix616]
website: 'https://github.com/RedstoneWorld/BungeeSpeak'
commands:
  ts:
    description: BungeeSpeak commands
    usage: Type /ts for help.
  tsa:
    description: BungeeSpeak admin commands
    usage: Type /tsa for help.
permissions:
  bukkitspeak.*:
    description: Gives access to all BungeeSpeak commands and messages.
    default: op
    children:
      bukkitspeak.commands.*: true
      bukkitspeak.messages.*: true
  bukkitspeak.moderator:
    description: Gives access to all user commands, all the messages and some admin commands.
    children:
      bukkitspeak.commands.user: true
      bukkitspeak.commands.channelkick: true
      bukkitspeak.commands.reload: true
      bukkitspeak.commands.status: true
      bukkitspeak.messages.*: true
  bukkitspeak.user:
    description: Gives access to most of the user commands and all messages.
    children:
      bukkitspeak.commands.help: true
      bukkitspeak.commands.list: true
      bukkitspeak.commands.mute: true
      bukkitspeak.commands.chat: true
      bukkitspeak.commands.pm: true
      bukkitspeak.commands.reply: true
      bukkitspeak.commands.info: true
      bukkitspeak.messages.*: true
  bukkitspeak.commands.*:
    description: Gives access to all BungeeSpeak commands.
    children:
      bukkitspeak.commands.user: true
      bukkitspeak.commands.admin: true
  bukkitspeak.commands.user:
    description: Gives access to all user commands.
    children:
      bukkitspeak.commands.help: true
      bukkitspeak.commands.list: true
      bukkitspeak.commands.mute: true
      bukkitspeak.commands.broadcast: true
      bukkitspeak.commands.chat: true
      bukkitspeak.commands.pm: true
      bukkitspeak.commands.reply: true
      bukkitspeak.commands.poke: true
      bukkitspeak.commands.info: true
  bukkitspeak.commands.admin:
    description: Gives access to all admin commands.
    children:
      bukkitspeak.commands.ban: true
      bukkitspeak.commands.kick: true
      bukkitspeak.commands.channelkick: true
      bukkitspeak.commands.set: true
      bukkitspeak.commands.status: true
      bukkitspeak.commands.reload: true
  bukkitspeak.commands.help:
    description: Allows you to show BungeeSpeak's help menu.
    default: true
  bukkitspeak.commands.list:
    description: Allows you to use /ts list.
  bukkitspeak.commands.mute:
    description: Allows you to use /ts mute.
  bukkitspeak.commands.broadcast:
    description: Allows you to use /ts broadcast <message>.
  bukkitspeak.commands.chat:
    description: Allows you to use /ts chat <message>.
  bukkitspeak.commands.pm:
    description: Allows you to use /ts pm target <message>.
  bukkitspeak.commands.reply:
    description: Allows you to use /ts r(eply) <message>.
  bukkitspeak.commands.poke:
    description: Allows you to use /ts poke <target> <message>.
  bukkitspeak.commands.info:
    description: Allows you to use /ts info.
  bukkitspeak.commands.ban:
    description: Allows you to use /tsa ban <target> (reason).
  bukkitspeak.commands.kick:
    description: Allows you to use /tsa kick <target> (reason).
  bukkitspeak.commands.channelkick:
    description: Allows you to use /tsa channelkick <target> (reason).
  bukkitspeak.commands.set:
    description: Allows you to use /tsa set (property) (value).
  bukkitspeak.commands.status:
    description: Allows you to use /tsa status.
  bukkitspeak.commands.reload:
    description: Allows you to use /tsa reload.
  bukkitspeak.messages.*:
    description: Allows you to see all messages.
    children:
      bukkitspeak.messages.join: true
      bukkitspeak.messages.leave: true
      bukkitspeak.messages.channelenter: true
      bukkitspeak.messages.channelleave: true
      bukkitspeak.messages.broadcast: true
      bukkitspeak.messages.chat: true
      bukkitspeak.messages.pm: true
  bukkitspeak.messages.join:
    description: Displays a message when somebody joined TeamSpeak.
  bukkitspeak.messages.leave:
    description: Displays a message when somebody left TeamSpeak.
  bukkitspeak.messages.channelenter:
    description: Displays a message when somebody entered the channel BungeeSpeak is listening to.
  bukkitspeak.messages.channelleave:
    description: Displays a message when somebody left the channel BungeeSpeak is listening to.
  bukkitspeak.messages.broadcast:
    description: Shows you messages which were broadcasted on TeamSpeak.
  bukkitspeak.messages.chat:
    description: Shows you chat messages in the channel BungeeSpeak is listening to.
  bukkitspeak.messages.pm:
    description: Shows you a message if somebody replies to your private message.
  bukkitspeak.sendteamspeak.*:
    description: All messages will be sent to TeamSpeak.
    default: true
    children:
      bukkitspeak.sendteamspeak.chat: true
      bukkitspeak.sendteamspeak.join: true
      bukkitspeak.sendteamspeak.quit: true
      bukkitspeak.sendteamspeak.kick: true
      bukkitspeak.sendteamspeak.ban: true
  bukkitspeak.sendteamspeak.chat:
    description: Sends messages of this user to TeamSpeak if SendChatToTeamspeak is set in the config.
  bukkitspeak.sendteamspeak.join:
    desctiption: Sends a Teamspeak message when the user joins the Minecraft server.
  bukkitspeak.sendteamspeak.quit:
    description: Sends a Teamspeak message when the user leaves the Minecraft server.
  bukkitspeak.sendteamspeak.kick:
    description: Sends a Teamspeak message when the user gets kicked from the Minecraft server.
  bukkitspeak.sendteamspeak.ban:
    description: Sends a Teamspeak message when the user gets banned from the Minecraft server.
